services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_ADMIN: ${DB_ADMIN}
    secrets:
      - db_password
      - db_root_password
    restart: always
    volumes: 
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_ADMIN_EMAIL: ${DB_ADMIN_EMAIL}
      DB_ADMIN: ${DB_ADMIN}
      DB_USER_EMAIL: ${DB_ADMIN_EMAIL}
    secrets:
      - db_password
      - db_root_password
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    ports:
      - "8443:8443"
      # - "8080:80"

volumes:
  mariadb_data: # just declare named volume for mariadb
  wordpress_data: 

networks:
  inception:
    driver: bridge #bridge bridge network is the default network type for containers on a single Docker host (this computer).

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt


# structure of the docker-compse.yml
# There are 3 service blocks: mariadb, wordpress and nginx
# In each service block, we have to set the name and the location of Dockerfile
# restart makes sure that the container autonatically restarts if it crashes or reboots.

# Network:A Docker network lets containers talk to each other by nam
# -> No network means containers are isolated and can't find each other 
# Volume: A volume is persistent storage used by a container.
# -> No volume means the loss of data when the continer stops 
# -> list only volume names (not path) under top-level volumes
# -> volumes in service should be listed "-" 