# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Dockerfile                                         :+:    :+:             #
#                                                      +:+                     #
#    By: nnarimatsu <nnarimatsu@student.codam.nl      +#+                      #
#                                                    +#+                       #
#    Created: 2025/07/22 10:42:45 by nnarimatsu    #+#    #+#                  #
#    Updated: 2025/07/22 10:43:41 by nnarimatsu    ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

FROM debian:bullseye

CMD ["sleep", "infinity"]